Add ability to use custom labels in SpecFlow plugin
allure-framework/allure-csharp pull request #284
Opened 2022-08-01 12:17 UTC by evgeniy-skt

### Context
Can't use Layer, AllureId fields with SpecFlow Plugin

#### Checklist
- [ ] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2022-08-01 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/allure-framework/allure-csharp?pullRequest=284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/allure-framework/allure-csharp?pullRequest=284) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: evgeniy-skt<br/>:x: alekskulakov<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/allure-framework/allure-csharp?pullRequest=284) it.</sub>

2022-08-03 16:08 UTC, neparij requested changes

2022-08-03 16:08 UTC, neparij commented
Hello guys! We are very glad to see your contributions.

Sounds funny because I pushed almost the same changes recently (https://github.com/allure-framework/allure-csharp/commit/f5ac293d084e5479fa0fdc7fe3354059d0795a3a) :)

Your PR looks really nice, just need to make some changes on review.
I will be glad to see you in the list of contributors!

🍕 ❤️

2022-08-03 16:11 UTC, neparij commented on Allure.Features/allureConfig.json
> +      "label": "(.+)\\((.+)\\)"
Also, you can use internal property in PluginConfiguration this way:
```csharp
internal string label => "^label:([\\w]+):(.+)";
```

2022-08-05 14:14 UTC, alekskulakov commented on Allure.Net.Commons/Model/allure2.Extensions.cs
> +        public static Label CustomLabel(string key, string value)
fixed

2022-08-05 14:15 UTC, alekskulakov commented on Allure.Features/allureConfig.json
> +      "label": "(.+)\\((.+)\\)"
Fixed regex.

2022-08-05 14:20 UTC, alekskulakov commented on Allure.Features/allureConfig.json
> +      "label": "(.+)\\((.+)\\)"
And I'm not sure about 
> internal string label => "^label:([\\w]+):(.+)";

Do we really need this? In this case we can't customize a regex pattern in the config file.

2022-08-09 10:30 UTC, neparij approved these changes

2022-09-01 11:18 UTC, merged