Add AllureId attribute
allure-framework/allure-csharp pull request #291
Opened 2022-08-31 08:30 UTC by alekskulakov

### Context
Added new Allure NUnit attribute because it's very inconvenient to write `[AllureLabel("AS_ID", "123")]` for every test.

#### Checklist
- [ ] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2022-09-01 14:19 UTC, baev requested changes

2022-09-01 14:19 UTC, baev commented on Allure.NUnit/Attributes/AllureIdAttribute.cs
> +            testResult.labels.Add(new Label {name = "AS_ID", value = Id.ToString()});
use `ALLURE_ID` instead (`AS_ID` supported but deprecated)

2022-09-01 15:34 UTC, alekskulakov commented on Allure.NUnit/Attributes/AllureIdAttribute.cs
> +            testResult.labels.Add(new Label {name = "AS_ID", value = Id.ToString()});
Fixed

2022-09-05 13:50 UTC, baev approved these changes
LGTM

2022-09-19 08:13 UTC, merged