Update Harmony and MonoMod to support .NET 8
allure-framework/allure-csharp pull request #449
Opened 2024-02-07 11:50 UTC by TonEnfer

### Context

#### Checklist
- [ ] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2024-02-29 10:17 UTC, delatrie requested changes
Hi, @TonEnfer !
Thank you for the contribution!

Let's update straight to Harmony 2.3.0 (it was released a couple of days ago).

2024-02-29 10:17 UTC, delatrie commented on Allure.SpecFlowPlugin/Allure.SpecFlowPlugin.csproj
> +        <PackageReference Include="MonoMod.Utils" Version="25.0.4" />
Harmony 2.3.0 already includes MonoMod.Utils v25.0.4+. We can remove this line now. Same for xUnit

2024-03-04 07:08 UTC, delatrie approved these changes

2024-03-04 07:20 UTC, merged

2024-03-18 13:42 UTC, AlexBar commented
Could you guys update nuget package to include these changes?

2024-04-02 12:37 UTC, delatrie commented
@AlexBar Sorry for the delay. Version 2.12.0 that contains the fix has just been released!